```{r}
#| message: false
#| include: false
#| label: cost-per-ticket-source
source(here::here("highest-gross-tours-decade-r.R"))
```


```{r}
#| label: cost-per-ticket-attendance
url2 <-
  "https://en.wikipedia.org/wiki/List_of_most-attended_concert_tours"

url_bow2 <- polite::bow(url2)
url_bow2

ind_html2 <-
  polite::scrape(url_bow2) |>  # scrape web page
  rvest::html_nodes("table.wikitable") |> # pull out specific table
  rvest::html_table(fill = TRUE)

ind_tab2 <-
  ind_html2[[2]] |>
  janitor::clean_names() |>
  dplyr::mutate(tickets_sold = as.numeric(str_replace(tickets_sold, " million.*", "")) * 1e6)

tours_by_decade2 <-
  tours_by_decade |>
  dplyr::mutate(
    tour_title = case_when(
      tour_title == "Music of the Spheres World Tour †" ~ "Music of the Spheres World Tour",
      tour_title == "The Garth Brooks World Tour" ~ "The Garth Brooks World Tour (1996–1998)",
      tour_title == "Steel Wheels Tour" ~ "Steel Wheels/Urban Jungle Tour",
      .default = tour_title
    )
  )

cost_per <-
  left_join(ind_tab2, tours_by_decade2, join_by(tour_title))
```

```{r}
#| results: hide
#| out.width: 400px
#| dpi: 300
#| fig.show: hide
#| fig.path: "../images/"
#| label: cost-per-ticket-scatterplot
cost_per |>
  mutate(cost_per = adjusted_gross_in_2022_dollar / tickets_sold) |>
  ggplot(aes(x = year, y = cost_per)) +
  geom_point() +
  geom_smooth(method = "lm")
```