```{r}
source(here::here("setup.R"))

url <-
  "https://en.wikipedia.org/wiki/List_of_highest-grossing_concert_tours"

url_bow <- polite::bow(url)
url_bow

ind_html <-
  polite::scrape(url_bow) |>
  rvest::html_nodes("table.wikitable") |>
  rvest::html_table(fill = TRUE)

annual_hi_gross_tours <- 
  ind_html[[9]] |>
  clean_names()

combine_data <- function(ind_html_list) {
  # Initialize an empty tibble
  combined_data <- tibble()
  
  # Loop through the ind_html_list and append each element to the combined_data
  for (i in 4:8) {
    extracted_data <- ind_html_list[[i]] |> clean_names()
    combined_data <- bind_rows(combined_data, extracted_data)
  }
  
  return(combined_data)
}

annual_hi_gross_tours <- combine_data(ind_html)

tours_by_decade <-
  annual_hi_gross_tours |>
  dplyr::mutate(across(
    c(adjusted_gross_in_2022_dollar,
      averagegross,
      actual_gross),
    ~ as.numeric(str_replace_all(.x, "[$,]", ""))
  )) |>
  mutate(
    start_year = str_sub(year_s, start = 1, end = 4),
    year = lubridate::ymd(start_year, truncated = 2L)
  ) |>
  mutate(
    decade = paste0(str_sub(
      as.factor(floor_date(year, years(10))), start = 1, end = 4), "s"),
    tour_title = case_when(tour_title == "The Eras Tour †" ~ "The Eras Tour",
                           tour_title == "Music of the Spheres World Tour †" ~ "Music of the Spheres World Tour",
                           tour_title == "After Hours til Dawn Tour †" ~ "After Hours til Dawn Tour",
                           tour_title == "Summer Carnival †" ~ "Summer Carnival",
                           tour_title == "Global Stadium Tour" ~ "Global Stadium",
                           .default = tour_title),
    adjusted_gross_in_2022_dollar = case_when(artist == "Taylor Swift" & tour_title == "The Eras Tour" ~ 2400000000,
                                              .default = adjusted_gross_in_2022_dollar),
    title = paste0(artist, " - ", tour_title))
```

```{r}
#| error: true
tours_1980s <-
  tours_by_decade |> 
  filter(decade == "1980s") |> 
  mutate(image = case_when(title == "Bruce Springsteen and the E Street Band - Born in the U.S.A. Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1980s/bruce.jpg",
                           title == "David Bowie - Glass Spider Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1980s/bowie.jpg",
                           title == "Genesis - Invisible Touch Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1980s/genesis.jpg",
                           title == "Michael Jackson - Bad" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1980s/michael.jpg",
                           title == "Pink Floyd - A Momentary Lapse of Reason Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1980s/pf.jpg",
                           title == "The Rolling Stones - The Rolling Stones American Tour 1981" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1980s/stones_steel.jpg",
                           title == "The Rolling Stones - Steel Wheels Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1980s/stones_america.jpg",
                           title == "The Jacksons - Victory Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1980s/jacksons.jpg",
                           title == "Tina Turner - Break Every Rule World Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1980s/tina.jpg",
                           title == "U2 - The Joshua Tree Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1980s/u2.jpg"))

tours_1980s |> 
  ggplot(
       aes(
         x = fct_reorder(title, adjusted_gross_in_2022_dollar),
         y = adjusted_gross_in_2022_dollar,
       )) +
  geom_col_pattern(
    aes(pattern_filename = fct_reorder(image, rank)),
    pattern = "image",
    alpha = 0.8,
    pattern_type = "expand"
  ) +
  scale_pattern_filename_discrete(
    choices = tours_1980s$image
    ) +
  scale_x_discrete(
    labels = function(x)
      str_wrap(x, width = 10)
  ) +
  labs(title = "Top 10 highest-grossing tours of the 2020s") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        legend.position = "none",
        title = element_text(size = 16,
                         family = "abril-fatface",
                         hjust = 0.5,
                         color = "#1D1E3C"),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), 
                                "inches")) +
  coord_flip() +
  geom_text(aes(label = paste0(round(adjusted_gross_in_2022_dollar/1e6, 0), "M"),
            hjust = -0.1)) +
  ylim(0, 2600000000) -> bar_1980s

save(bar_1980s, file = "images/highest-grossing-tour-bar-1980s.rdata")
```

```{r}
tours_1990s <-
  tours_by_decade |> 
  filter(decade == "1990s") |> 
  mutate(image = case_when(artist == "Celine Dion" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1990s/02dion.jpg",
                           artist == "Eagles" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1990s/04eagles.jpg",
                           artist == "Garth Brooks" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1990s/01brooks.jpg",
                           artist == "Michael Jackson" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1990s/05michael.jpg",
                           artist == "Pink Floyd" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1990s/09pf.jpg",
                           artist == "The Rolling Stones" & tour_title == "Bridges to Babylon Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1990s/08stones_babylon.jpg",
                           artist == "The Rolling Stones" & tour_title == "Voodoo Lounge Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1990s/10stones_voodoo.jpg",
                           artist == "Tina Turner" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1990s/03tina.jpg",
                           artist == "U2" & tour_title == "PopMart Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1990s/07u2_pop.jpg",
                           artist == "U2" & tour_title == "Zoo TV Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/1990s/06u2_zoo.jpg"))

tours_1990s |> 
  ggplot(
       aes(
         x = fct_reorder(title, adjusted_gross_in_2022_dollar),
         y = adjusted_gross_in_2022_dollar,
       )) +
  geom_col_pattern(
    aes(pattern_filename = fct_reorder(image, rank)),
    pattern = "image",
    alpha = 0.8,
    pattern_type = "expand"
  ) +
  scale_pattern_filename_discrete(
    choices = tours_1990s$image
    ) +
  scale_x_discrete(
    labels = function(x)
      str_wrap(x, width = 20)
  ) +
  labs(title = "Top 10 highest-grossing tours of the 1990s") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        legend.position = "none",
        title = element_text(size = 16,
                         family = "abril-fatface",
                         hjust = 0.5,
                         color = "#1D1E3C"),
        plot.margin = unit(c(0, 0, 0, 0.15), "inches")) +
  coord_flip() +
  geom_text(aes(label = paste0(round(adjusted_gross_in_2022_dollar/1e6, 0), "M"),
            hjust = -0.1)) +
  ylim(0, 2600000000) -> bar_1990s

ggsave(
  filename = here::here("images", "bar_1990s.png"),
  plot = bar_1990s,
  device = png,
  path = NULL,
  scale = 1,
  width = 14,
  height = 8,
  units = "in",
  dpi = 300,
  limitsize = TRUE,
  bg = NULL
)
```

```{r}
tours_2000s <-
  tours_by_decade |> 
  filter(decade == "2000s") |> 
  mutate(image = case_when(title == "The Rolling Stones - A Bigger Bang Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2000s/stones_bang.jpg",
                           title == "Madonna - Sticky & Sweet Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2000s/madonna.jpg",
                           title == "U2 - Vertigo Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2000s/u2_vertigo.jpg",
                           title == "The Police - The Police Reunion Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2000s/police.jpg",
                           title == "U2 - U2 360° Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2000s/u2_360.jpg",
                           title == "The Rolling Stones - Licks Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2000s/stones_lick.jpg",
                           title == "Celine Dion - Taking Chances World Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2000s/dion.jpg",
                           title == "Cher - Living Proof: The Farewell Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2000s/cher.jpg",
                           title == "AC/DC - Black Ice World Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2000s/acdc.jpg",
                           title == "Bruce Springsteen and the E Street Band - Magic Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2000s/bruce.jpg"))

tours_2000s |> 
  ggplot(
       aes(
         x = fct_reorder(title, adjusted_gross_in_2022_dollar),
         y = adjusted_gross_in_2022_dollar,
       )) +
  geom_col_pattern(
    aes(pattern_filename = fct_reorder(image, rank)),
    pattern = "image",
    alpha = 0.8,
    pattern_type = "expand"
  ) +
  scale_pattern_filename_discrete(
    choices = tours_2000s$image
    ) +
  scale_x_discrete(
    labels = function(x)
      str_wrap(x, width = 20)
  ) +
  labs(title = "Top 10 highest-grossing tours of the 2000s") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        legend.position = "none",
        title = element_text(size = 16,
                         family = "abril-fatface",
                         hjust = 0.5,
                         color = "#1D1E3C"),
        plot.margin = unit(c(0, 0, 0, 0.15), "inches")) +
  coord_flip() +
  geom_text(aes(label = paste0(round(adjusted_gross_in_2022_dollar/1e6, 0), "M"),
            hjust = -0.1)) +
  ylim(0, 2600000000) -> bar_2000s

ggsave(
  filename = here::here("images", "bar_2000s.png"),
  plot = bar_2000s,
  device = png,
  path = NULL,
  scale = 1,
  width = 14,
  height = 8,
  units = "in",
  dpi = 300,
  limitsize = TRUE,
  bg = NULL
)
```

```{r}
tours_2010s <-
  tours_by_decade |> 
  filter(decade == "2010s") |> 
  mutate(image = case_when(title == "Bruno Mars - 24K Magic World Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2010s/bruno.jpg",
                           title == "Coldplay - A Head Full of Dreams Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2010s/coldplay.jpg",
                           title == "The Rolling Stones - No Filter Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2010s/stones.jpg",
                           title == "Ed Sheeran - ÷ Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2010s/ed.jpg",
                           title == "Guns N' Roses - Not in This Lifetime... Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2010s/gnr.jpg",
                           title == "Metallica - WorldWired Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2010s/metallica.jpg",
                           title == "Pink - Beautiful Trauma World Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2010s/pink.jpg",
                           title == "Roger Waters - The Wall" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2010s/waters.jpg",
                           title == "U2 - The Joshua Tree Tours 2017 and 2019" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2010s/u2_josh.jpg",
                           title == "U2 - U2 360° Tour" ~ "~/R/taylor-swift-tour/notebooks/tours-images/2010s/u2_360.jpg"))

tours_2010s |> 
  ggplot(
       aes(
         x = fct_reorder(title, adjusted_gross_in_2022_dollar),
         y = adjusted_gross_in_2022_dollar,
       )) +
  geom_col_pattern(
    aes(pattern_filename = fct_reorder(image, rank)),
    pattern = "image",
    alpha = 0.8,
    pattern_type = "expand"
  ) +
  scale_pattern_filename_discrete(
    choices = tours_2010s$image
    ) +
  scale_x_discrete(
    labels = function(x)
      str_wrap(x, width = 20)
  ) +
  labs(title = "Top 10 highest-grossing tours of the 2010s") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        legend.position = "none",
        title = element_text(size = 16,
                         family = "abril-fatface",
                         hjust = 0.5,
                         color = "#1D1E3C"),
         plot.margin = unit(c(0, 0, 0, 0.15), "inches")) +
  coord_flip() +
  geom_text(aes(label = paste0(round(adjusted_gross_in_2022_dollar/1e6, 0), "M"),
            hjust = -0.1)) +
  ylim(0, 2600000000) -> bar_2010s

ggsave(
  filename = here::here("images", "bar_2010s.png"),
  plot = bar_2010s,
  device = png,
  path = NULL,
  scale = 1,
  width = 14,
  height = 8,
  units = "in",
  dpi = 300,
  limitsize = TRUE,
  bg = NULL
)
```

```{r}
tours_2020s <-
  tours_by_decade |> 
  filter(decade == "2020s") |> 
  mutate(image = case_when(artist == "Beyoncé" ~ "~/R/taylor-swift-tour/notebooks/tours-images/beyonce2.jpg",
                           artist == "Harry Styles" ~ "~/R/taylor-swift-tour/notebooks/tours-images/harry2.jpg",
                           artist == "Coldplay" ~ "~/R/taylor-swift-tour/notebooks/tours-images/coldplay.jpg",
                           artist == "Ed Sheeran" ~ "~/R/taylor-swift-tour/notebooks/tours-images/ed2.jpg",
                           artist == "Elton John" ~ "~/R/taylor-swift-tour/notebooks/tours-images/elton2.jpg",
                           artist == "Bad Bunny" ~ "~/R/taylor-swift-tour/notebooks/tours-images/bunny2.jpg",
                           artist == "Pink" ~ "~/R/taylor-swift-tour/notebooks/tours-images/pink2.jpg",
                           artist == "Red Hot Chili Peppers" ~ "~/R/taylor-swift-tour/notebooks/tours-images/rhcp.jpg",
                           artist == "The Weeknd" ~ "~/R/taylor-swift-tour/notebooks/tours-images/wknd.jpg",
                           artist == "Taylor Swift" ~ "~/R/taylor-swift-tour/notebooks/tours-images/taylor2.jpg"))

tours_2020s$artist <- factor(tours_2020s$artist, levels = c("Red Hot Chili Peppers", "Pink", "The Weeknd", "Bad Bunny", "Ed Sheeran", "Elton John", "Beyoncé", "Harry Styles", "Coldplay", "Taylor Swift"))

tours_2020s |> 
  ggplot(
       aes(
         x = fct_reorder(title, adjusted_gross_in_2022_dollar),
         y = adjusted_gross_in_2022_dollar,
       )) +
  geom_col_pattern(
    aes(pattern_filename = fct_reorder(image, -adjusted_gross_in_2022_dollar)),
    pattern = "image",
    alpha = 0.8,
    pattern_type = "expand"
  ) +
  scale_pattern_filename_discrete(
    choices = tours_2020s$image
    ) +
  scale_x_discrete(
    labels = function(x)
      str_wrap(x, width = 20)
  ) +
  labs(title = "Top 10 highest-grossing tours of the 2020s") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_blank(), 
        legend.position = "none",
        title = element_text(size = 16,
                         family = "abril-fatface",
                         hjust = 0.5,
                         color = "#1D1E3C"),
         plot.margin = unit(c(0, 0, 0, 0.15), "inches")) +
  coord_flip() +
  geom_text(aes(label = paste0(round(adjusted_gross_in_2022_dollar/1e6, 0), "M"),
            hjust = -0.1)) +
  ylim(0, 2600000000) -> bar_2020s

ggsave(
  filename = here::here("images", "bar_2020s.png"),
  plot = bar_2020s,
  device = png,
  path = NULL,
  scale = 1,
  width = 14,
  height = 8,
  units = "in",
  dpi = 300,
  limitsize = TRUE,
  bg = NULL
)
```