<details><summary>See R code</summary>

::: {.callout-tip}
## The Eras Tour Dates and Venues

```{r}
#| message: false
#| warning: false
# To clean data
library(tidyverse)
library(janitor)

# To scrape data
library(rvest)
library(httr)
library(polite)

# To geocode data
library(tidygeocoder)

# To visualize data
library(leaflet)
```

```{r}
url <-
  "https://www.sportskeeda.com/pop-culture/taylor-swift-2023-the-eras-tour-ticket-cities-and-dates"
```

```{r}
#| message: false
url_bow <- polite::bow(url)
url_bow
```

```{r}
ind_html <-
  polite::scrape(url_bow) %>%  # scrape web page
  rvest::html_nodes("tbody") %>% # pull out specific table
  rvest::html_table(fill = TRUE) %>% 
  bind_rows() %>% 
  row_to_names(row_number = 1) %>% 
  clean_names()
```

```{r}
#| message: false
ind_html_geo <-
  ind_html %>% 
  geocode(venue, method = 'osm', lat = latitude , long = longitude)

ind_html_geo <-
  ind_html_geo %>% 
  mutate(latitude = case_when(venue == "Empower Field at Mile Hi" ~ 39.74359,
                              venue == "Johan Cruyff Arena" ~ 52.3143,
                              .default = latitude),
         longitude = case_when(venue == "Empower Field at Mile Hi" ~ -105.01968,
                              venue == "Johan Cruyff Arena" ~ 4.94187,
                              .default = longitude))
```


```{r}
#| results: false
leaflet() %>%
  addProviderTiles("Stadia.StamenWatercolor",
                   group = "Stadia.StamenWatercolor") %>%
  addMarkers(
    data = ind_html_geo,
    label = paste(
      "Venue: ",
      ind_html_geo$venue,
      "<br>",
      "City: ",
      ind_html_geo$city,
      "<br>",
      "Date: ",
      ind_html_geo$date
    ) %>%
      lapply(htmltools::HTML)
  )
```

:::
</details>
